### ISSUE TITLE
AttributeError: 'Star' object has no attribute 'get_temperature'

### ISSUE THREAD

**Issue by Krypton-Nova** [tschoppi/starsystem-gen#66]
I got the following error on running the generator:

**500 Internal Server Error**

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "...\Python-3.6\lib\site-packages\cherrypy\_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "...\Python-3.6\lib\site-packages\cherrypy\_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "...\Python-3.6\lib\site-packages\cherrypy\lib\encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "...\Python-3.6\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "server.py", line 71, in starsystem
    mysys = starsys.StarSystem(**arguments)
  File "...\Desktop\starsystem-gen-master\gurpsspace\starsystem.py", line 18, in __init__
    self.stars = self.generate_stars(self.num_stars)
  File "...\Desktop\starsystem-gen-master\gurpsspace\starsystem.py", line 119, in generate_stars
    temporary_stars.append(star.Star(age=self.age))
  File "...\Desktop\starsystem-gen-master\gurpsspace\star.py", line 25, in __init__
    self.__star_type = self.get_star_type()
  File "...\Desktop\starsystem-gen-master\gurpsspace\star.py", line 219, in get_star_type
    key=lambda i: abs(StEvoTable['temp'][i] - self.get_temperature()))
  File "...\Desktop\starsystem-gen-master\gurpsspace\star.py", line 219, in <lambda>
    key=lambda i: abs(StEvoTable['temp'][i] - self.get_temperature()))
AttributeError: 'Star' object has no attribute 'get_temperature'

Powered by CherryPy 18.0.0

**Comment by tschoppi** [comment]
Woopsie. Thanks for the bug report, we'll have a look at it!
